### 搜索课程
GET {{search_host}}/search/course/list?pageNo=1&keywords=spring
Content-Type: application/json

### 申请验证码
POST localhost:63075/checkcode/pic

### 校验验证码
POST localhost:63075/checkcode/verify?key=checkcode4506b95bddbe46cdb0d56810b747db1b&code=70dl

